### ISSUE TITLE
Create option to pass rc cofig file to pylint

### ISSUE THREAD

**Issue by ricardochaves** [ricardochaves/python-lint#2]
http://pylint.pycqa.org/en/stable/user_guide/run.html#command-line-options

**Comment by lukeorland** [comment]
That would be help for isort as well. It doesn't seem to be sourcing the `pyproject.toml` at the root of my repo.

**Comment by ricardochaves** [comment]
@lukeorland , I am also having trouble with `Isort`. On my Mac it works perfectly, but on the pipe it fails.
I found this [Issues](https://github.com/timothycrosley/isort/issues/725). I did a test as [this review](https://github.com/timothycrosley/isort/issues/725#issuecomment-406887395) says. It worked for me.

Anyway, I added more options in Action. You can now pass any parameter to any lib. Take a look at README.md

I am closing this issue, feel free to open another about Isort if you continue to have problems.
